#  导入numpy库并简写为 np 

In [4]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 9., 3., 2.],
       [2., 3., 9., 5.],
       [6., 3., 0., 3.]])

In [5]:
#2. 打印numpy的版本和配置说明 
np.__version__

'1.14.3'

In [8]:
#3. 创建一个长度为10的空向量 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 4. 如何找到任何一个数组的内存大小？ 
a = np.ones(10)
a.size*a.itemsize

80

In [13]:
# 5. 如何从命令行得到numpy中add函数的说明文档? 
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add

In [16]:
# 6. 创建一个长度为10并且除了第五个值为1的空向量 
a = np.zeros(10)
a[4] =1 
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [21]:
# 7. 创建一个值域范围从10到49的向量
a = np.arange(10,50,1)

In [25]:
#* 8. 反转一个向量(第一个元素变为最后一个) 
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [26]:
# 9. 创建一个 3x3 并且值从0到8的矩阵
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
#* 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

In [37]:
#* 11. 创建一个 3x3 的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# 12. 创建一个 3x3x3的随机数组 
a = np.random.random((3,3,3))
a

array([[[0.35175626, 0.31831024, 0.14076617],
        [0.66857971, 0.40751789, 0.14742504],
        [0.86670693, 0.95371568, 0.77490512]],

       [[0.47052288, 0.10303061, 0.35500604],
        [0.35857084, 0.19412401, 0.97158994],
        [0.87942869, 0.92330819, 0.39293214]],

       [[0.34720549, 0.39124052, 0.57113271],
        [0.89748518, 0.87971821, 0.77012919],
        [0.56790801, 0.48941756, 0.64805354]]])

In [48]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值
a = np.random.random((10,10))
print(a)
print(a.max())
print(np.min(a))

[[0.65261006 0.76636988 0.74157618 0.09970147 0.70953625 0.32814386
  0.67224661 0.47211427 0.92055413 0.7667196 ]
 [0.7020538  0.43996154 0.871394   0.9635522  0.42739811 0.36398095
  0.32538245 0.90359685 0.50968037 0.94619641]
 [0.53077881 0.98809288 0.50251161 0.59011044 0.77262521 0.51862683
  0.62496826 0.07798723 0.21317342 0.86764646]
 [0.28672981 0.99295264 0.04134218 0.40560789 0.02626596 0.9015763
  0.99555026 0.45604775 0.20728737 0.88866499]
 [0.26003707 0.34463019 0.1536581  0.44098724 0.53904621 0.73245613
  0.40417041 0.95184299 0.43854684 0.58264352]
 [0.55395225 0.83787768 0.96499429 0.22469091 0.15863607 0.86894538
  0.31383537 0.21696098 0.29461883 0.78616974]
 [0.78936851 0.48074402 0.90911491 0.79831246 0.43492251 0.81213922
  0.40119328 0.73086446 0.50304531 0.06968125]
 [0.2817194  0.73500917 0.26173071 0.08963963 0.95590716 0.86176812
  0.93567226 0.34854617 0.5577438  0.79600437]
 [0.15862974 0.35582999 0.97031836 0.87823401 0.92106749 0.03712162
  0.83762189 

In [49]:
# 14. 创建一个长度为30的随机向量并找到它的平均值 
a = np.random.random(30)
print(a)
print(np.mean(a))

[0.45340373 0.76001989 0.54540264 0.50261197 0.11206977 0.8787165
 0.83418145 0.08142973 0.43418202 0.31783641 0.32707494 0.82876386
 0.35268407 0.39371558 0.5633925  0.26236885 0.64913611 0.82944409
 0.10578929 0.01462691 0.80053099 0.28604993 0.44774849 0.16117174
 0.63918948 0.00169233 0.8951086  0.02123245 0.19763287 0.83620929]
0.45111388295879895


In [55]:
# 15.创建一二维数组，其中边界值为1，其余值为0
a = np.zeros((10,10))
print(a)
a[[0,-1],:] = 1 
a[1:-1,[0,-1]] = 1
a

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [59]:
# * 16. 对于一个存在在数组，如何添加一个用0填充的边界? 
a = np.ones((5,5))
print(a)
a = np.pad(a,pad_width=1,mode='constant',constant_values=0)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
0*np.nan
np.nan==np.nan
np.inf >np.nan
0.3==3*0.1

False

In [77]:
#* 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [81]:
#* 19. 创建一个8x8 的矩阵，并且设置成棋盘样式 
Z = np.zeros((8,8),dtype=int)
print(Z)    
Z[1::2,::2] = 1 
Z[::2,1::2] = 1 
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [90]:
#* 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [91]:
#* 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [93]:
#  22. 对一个5x5的随机矩阵做归一化
a = np.random.random((5,5))
print(a)
mins = a.min()
maxs = a.max()
b = (a-mins)/(maxs-mins)
print(b)

[[0.71868819 0.41814333 0.9891581  0.72874564 0.23024559]
 [0.90518253 0.81663335 0.0082203  0.75965114 0.69246778]
 [0.78572368 0.54793852 0.63484651 0.49198222 0.18517055]
 [0.38262533 0.86227749 0.87174306 0.69844859 0.99278401]
 [0.68459762 0.78260324 0.36741189 0.60851682 0.00903735]]
[[7.21606827e-01 4.16349928e-01 9.96317249e-01 7.31821961e-01
  2.25506274e-01]
 [9.11025080e-01 8.21087604e-01 0.00000000e+00 7.63212003e-01
  6.94975326e-01]
 [7.89693318e-01 5.48180092e-01 6.36450645e-01 4.91346488e-01
  1.79724528e-01]
 [3.80275066e-01 8.67447360e-01 8.77061335e-01 7.01049906e-01
  1.00000000e+00]
 [6.86981771e-01 7.86523954e-01 3.64823107e-01 6.09708150e-01
  8.29854406e-04]]


In [94]:
#* 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([("r", np.ubyte, 1),

("g", np.ubyte, 1),

("b", np.ubyte, 1),

("a", np.ubyte, 1)])

color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [98]:
#* 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 
print(np.dot(np.ones((5,3)),np.ones((3,2))))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [114]:
#* 25. 给定一个一维数组，对其在3到8之间的所有元素取反 
z = np.arange(11)
z[(z>3) & (z<8)]=z[(z>3) & (z<8)]*-1
print(z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [119]:
#* 33. 如何得到昨天，今天，明天的日期?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
yesterday

numpy.datetime64('2020-04-25')

In [120]:
#* 34. 如何得到所有与2016年7月对应的日期？ 
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [124]:
#36. 用五种不同的方法去提取一个随机数组的整数部分
a = np.random.uniform(0,10,(5,3))
print(a)
np.floor(a)

[[4.32203986 4.9697471  7.20602841]
 [8.02019261 6.24311375 4.45590577]
 [7.71528408 9.66742073 9.27565733]
 [5.14462689 7.01425289 4.78673282]
 [3.57559128 8.75081293 0.49700133]]


array([[4., 4., 7.],
       [8., 6., 4.],
       [7., 9., 9.],
       [5., 7., 4.],
       [3., 8., 0.]])

In [128]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 
np.zeros((5,5))+np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [131]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
np.random.random(10)

array([0.0978656 , 0.61362317, 0.89430642, 0.42859104, 0.70571087,
       0.51601987, 0.6346494 , 0.96299546, 0.17320983, 0.16375081])

In [136]:
# 40. 创建一个长度为10的随机向量，并将其排序 
a = np.random.random(10)
print(a)
a.sort()
print(a)

[0.54156893 0.36246244 0.98866687 0.06296126 0.00317451 0.92918125
 0.8353372  0.43862611 0.67856393 0.51957648]
[0.00317451 0.06296126 0.36246244 0.43862611 0.51957648 0.54156893
 0.67856393 0.8353372  0.92918125 0.98866687]


In [138]:
#* 42. 对于两个随机数组A和B，检查它们是否相等 
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
np.equal(a,b)
np.allclose(a,b)

False

In [141]:
#* 43. 创建一个只读数组
z = np.zeros(10)
z.flags.writeable= False
z[0]=1

ValueError: assignment destination is read-only

In [144]:
# 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
z = np.random.random((10,2))
x,y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)

In [146]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1 
a = np.random.random(10)
print(a)
a[a==a.max()] = 1 
print(a)

[0.78008077 0.95990951 0.46561703 0.06156658 0.16514173 0.44850262
 0.83308954 0.4121179  0.34081062 0.68928463]
[0.78008077 1.         0.46561703 0.06156658 0.16514173 0.44850262
 0.83308954 0.4121179  0.34081062 0.68928463]


In [151]:
#* 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
x1 = np.linspace(0,1,5)
y1 = np.linspace(0,1,5)
x,y = np.meshgrid(x1,y1)

print(x1)
print('\n')
print(x)
print('\n')
print(y1)
print('\n')
print(y)

[0.   0.25 0.5  0.75 1.  ]


[[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]


[0.   0.25 0.5  0.75 1.  ]


[[0.   0.   0.   0.   0.  ]
 [0.25 0.25 0.25 0.25 0.25]
 [0.5  0.5  0.5  0.5  0.5 ]
 [0.75 0.75 0.75 0.75 0.75]
 [1.   1.   1.   1.   1.  ]]


In [163]:
# 53. 如何将32位的浮点数(float)转换为对应的整数(integer)?
a = np.random.randint(0,10,(5,5))
b = a.astype(np.float32)
b[b[:,0].argsort()]

array([[4., 3., 4., 3., 6.],
       [4., 1., 8., 8., 4.],
       [6., 7., 8., 8., 4.],
       [7., 8., 7., 1., 3.],
       [8., 5., 6., 3., 2.]], dtype=float32)

NameError: name 'pd' is not defined