# initial

In [1]:
import numpy as np 

In [28]:
#创建数组
a = np.array([1,2,3])
b = np.array([1,2,3],dtype='int64')
c = np.ones((3,4))
d = np.arange(0,12,2).reshape((2,3))
e = np.linspace(0,9,4)
f = np.random.random((3,4))
print(d)
print(d.ndim)
print(d.size)
print(d.shape)
print(d.dtype)

[[ 0  2  4]
 [ 6  8 10]]
2
6
(2, 3)
int32


# calculate

In [32]:
# 运算
a = np.array([20,30,40,50])
b = np.arange(4)

In [33]:
c = a-b
c

array([20, 29, 38, 47])

In [34]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [37]:
10*np.sin(a)


array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [38]:
a < 25

array([ True, False, False, False])

In [41]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [42]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [65]:
a = np.ones(3)
b = np.linspace(0,np.pi,3)
c = a+b
d = np.exp(c)
d

array([ 2.71828183, 13.07623325, 62.90292428])

In [71]:
a = np.random.random((2,3))
a

array([[0.20773271, 0.75370318, 0.4205396 ],
       [0.84226844, 0.09120009, 0.64490925]])

In [72]:
a.sum()

2.960353283280532

In [73]:
a.min()

0.09120009384027339

In [74]:
a.max()

0.8422684424973902

In [75]:
b = np.arange(12).reshape((3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
b.sum(axis=0)

array([12, 15, 18, 21])

# 通用函数

sin,cos,exp等

In [77]:
B = np.arange(3)
B

array([0, 1, 2])

In [78]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [79]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [82]:
a = np.arange(12)**2                          # the first 12 square numbers
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [84]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )         # a bidimensional array of indices
a[j]    

array([[ 9, 16],
       [81, 49]], dtype=int32)